### ISSUE TITLE
Feature: Add "About" Section in Help Toolbar

### ISSUE THREAD

**Issue by rishikeshgmahajan** [rishikeshgmahajan/BrightnessMD#5]
In the help toolbar add an QAction with text "About". On clicking the QAction the new dialog must be executed.

Below is the empty help toolbar where the "About" QAction is to be added
![Image](https://github.com/user-attachments/assets/d40b1354-acab-4bce-9a3a-bd6dfc3dd495)

Dialog specifications:
1. Dialog title: About Brightness
2. Dialog Icon: Use the MEico.ico file from [ME_Icons](https://github.com/rishikeshgmahajan/BrightnessMD/tree/main/ME_Icons) folder.

The dialog must contain the MEIco.png, the name "Brightness" in bold or highlighted in particular way such that it gets attention, add the description of the markdown editor, add the Github repo link.
Also at the bottom of dialog add an "ok" button which also closes the dialog. the button must have the following generalized stylesheet for buttons
```css
QPushButton{
       border-radius:5px;
       padding:6px;
       border:1px solid #ccc;
       background:white;}
QPushButton:hover{
        border:1px solid royalblue;
        color:royalblue;}
```
